[package]
name = "proc_macro_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iter-object = { version = "*", path = "./iter-object/" }
